# Generated by Django 2.1.5 on 2019-01-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingelement',
            old_name='time',
            new_name='speed',
        ),
    ]
