# Generated by Django 2.1.5 on 2019-01-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0010_auto_20190130_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='groupjoin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='racemate.RunningGroup'),
        ),
    ]
