# Generated by Django 2.1.5 on 2019-02-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0011_message_groupjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='togroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message', to='racemate.RunningGroup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='groupjoin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Join', to='racemate.RunningGroup'),
        ),
    ]
