# Generated by Django 2.1.5 on 2019-02-17 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0012_auto_20190201_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nadawca', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Adresat', to=settings.AUTH_USER_MODEL, verbose_name='Adresat'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='togroup',
        ),
        migrations.AddField(
            model_name='message',
            name='togroup',
            field=models.ManyToManyField(blank=True, null=True, related_name='Message', to='racemate.RunningGroup', verbose_name='Wiadomość do grupy'),
        ),
    ]
