# Generated by Django 2.1.7 on 2019-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0014_auto_20190217_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='efficiency',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='r10',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='r15',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='r21',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='r3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='r42',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='r5',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
