# Generated by Django 2.1.7 on 2019-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0015_auto_20190313_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='written',
            field=models.BooleanField(default=False),
        ),
    ]
