# Generated by Django 2.1.7 on 2019-03-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0016_message_written'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='written',
            new_name='read',
        ),
    ]
