# Generated by Django 2.1.7 on 2019-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0017_auto_20190314_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
