# Generated by Django 2.1.5 on 2019-02-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racemate', '0013_auto_20190217_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='groupjoin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Join', to='racemate.RunningGroup'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='togroup',
        ),
        migrations.AddField(
            model_name='message',
            name='togroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Message', to='racemate.RunningGroup', verbose_name='Wiadomość do grupy'),
        ),
    ]
