# Generated by Django 2.1.5 on 2019-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_runninggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingelement',
            name='name',
            field=models.CharField(default='easy', max_length=255),
        ),
    ]
